### ISSUE TITLE
incorrect output with '#,##0.0' format

### ISSUE THREAD

**Issue by adamgundy** [SheetJS/ssf#10]
SSF.format( "#,##0.0", 0.99 ) gives a result of '0.1' - it should be '1.0'.

same applies down to 0.95, below that it works correctly. rounding issue?

**Comment by SegFaultx64** [comment]
I am also seeing this happening. What can I do to help get this fixed? Where in the code should I look, etc.?

**Comment by RichardCzechowski** [comment]
+1 to this.

**Comment by SegFaultx64** [comment]
I have a fix. I will submit a pull later this evening.

**Comment by RichardCzechowski** [comment]
:trophy:

**Comment by SegFaultx64** [comment]
I submitted a pull: #16 
It goes not seem like this project is super actively maintained right now so we my end up maintaining our own fork. If we do I will comment with a like here as it will likely not be under my personal profile.

**Comment by RichardCzechowski** [comment]
Great. Thanks for doing this. Those failing tests, unrelated to your changes?

**Comment by SegFaultx64** [comment]
Yeah, some of the tests timeout for unknown reasons occasionally. It was
happening before my changes were made.

On Mon, Jul 13, 2015 at 8:34 PM, Richard Czechowski <
notifications@github.com> wrote:

> Great. Thanks for doing this. Those failing tests, unrelated to your
> changes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SheetJS/ssf/issues/10#issuecomment-121098798>.
>



-- 
- Max Walker

**Comment by RichardCzechowski** [comment]
That's what I figured.  :+1:
