### ISSUE TITLE
Cannot place dollar sign after number

### ISSUE THREAD

**Issue by wilg** [SheetJS/ssf#19]
Trying to format a number like `3.14$` doesn't seem to work.

`#.00"$"` outputs `3.14`
`#.00$` outputs `3.14`
`#.00 $` outputs `3.14 $`, but the space is undesirable

**Comment by SheetJSDev** [comment]
For some reason that I cannot reproduce with any of the test files, a dollar sign after a numeric token was discarded.  Since none of the live test files match the old behavior, this was corrected.
