### ISSUE TITLE
$#,##0_);($#,##0);"-" does not work for negative numbers

### ISSUE THREAD

**Issue by tinkermachine** [SheetJS/ssf#40]
Format: $#,##0_);($#,##0);"-"

Current output: (2$,000)

Desired output: ($2,000)

**Comment by jgdovin** [comment]
This is a duplicate of #31

**Comment by tinkermachine** [comment]
Is there an update to this?

**Comment by SheetJSDev** [comment]
Fixed in 0.11.0
