### ISSUE TITLE
bug with the position of the $ in a negative number

### ISSUE THREAD

**Issue by ChubbyCub** [SheetJS/ssf#47]
I think this bug only happens with negative currency and only for numbers with four or more digits. For example, $(2,500.00) will get parsed into (2$,500.00). or $(12,500.00) will get parsed into (12$,500.00).

**Comment by tinkermachine** [comment]
Having the same issue. Seems like this has been hanging around for a bit. Any updates?

**Comment by SheetJSDev** [comment]
Fixed in 0.11.0
