### ISSUE TITLE
Extra contents of format ignored for numbers if contains @

### ISSUE THREAD

**Issue by snoopyjc** [SheetJS/ssf#56]
console.log(SSF.format('"a"@', 26))

Logs '26'

It should log 'a26'

`choose_fmt()` is returning [0, "General"]

**Comment by SheetJSDev** [comment]
This exactly follows Excel.  To verify, set cell A1 to 26 and set the format to `"a"@` -- you will see 26.  You can also try the function `=TEXT(26,"""a""@")`
