### ISSUE TITLE
Uncaught Error: unsupported format |#,###.##|

### ISSUE THREAD

**Issue by sarimarton** [SheetJS/ssf#91]
Hi

It seems the library doesn't like this:

```js
import ssf from 'ssf'

ssf.format('#,###.##', 123456678.92)
```

because I get this runtime error:

```
Uncaught Error: unsupported format |#,###.##|
```

**Comment by SheetJSDev** [comment]
This project has been folded into the main SheetJS repo, please report at https://git.sheetjs.com/sheetjs/sheetjs/issues
